# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ila_xdc.xdc

# Block Designs: bd/ILA_DEBUG/ILA_DEBUG.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG || ORIG_REF_NAME==ILA_DEBUG} -quiet] -quiet

# IP: bd/ILA_DEBUG/ip/ILA_DEBUG_c_accum_0_0/ILA_DEBUG_c_accum_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG_c_accum_0_0 || ORIG_REF_NAME==ILA_DEBUG_c_accum_0_0} -quiet] -quiet

# IP: bd/ILA_DEBUG/ip/ILA_DEBUG_c_counter_binary_0_0/ILA_DEBUG_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG_c_counter_binary_0_0 || ORIG_REF_NAME==ILA_DEBUG_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ILA_DEBUG/ip/ILA_DEBUG_xlconstant_0_0/ILA_DEBUG_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG_xlconstant_0_0 || ORIG_REF_NAME==ILA_DEBUG_xlconstant_0_0} -quiet] -quiet

# IP: bd/ILA_DEBUG/ip/ILA_DEBUG_ila_0_0/ILA_DEBUG_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG_ila_0_0 || ORIG_REF_NAME==ILA_DEBUG_ila_0_0} -quiet] -quiet

# IP: bd/ILA_DEBUG/ip/ILA_DEBUG_register_0_0/ILA_DEBUG_register_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ILA_DEBUG_register_0_0 || ORIG_REF_NAME==ILA_DEBUG_register_0_0} -quiet] -quiet

# XDC: e:/VIVADO_2022/ARTIX_A7_35T/Axi_stream_debug_ILA/Axi_stream_debug_ILA.gen/sources_1/bd/ILA_DEBUG/ILA_DEBUG_ooc.xdc
